In [11]:
import torch

x = torch.tensor([[1.0, 2.0, 3.0, 4.0, 5.0], [1, 1, 1, 1, 1]])

mask = x <= torch.tensor([[2], [2]])
# y = x <= torch.tensor([[2]])

print(mask)
print(x)
x[mask] = float('-inf')
print(x)

tensor([[ True,  True, False, False, False],
        [ True,  True,  True,  True,  True]])
tensor([[1., 2., 3., 4., 5.],
        [1., 1., 1., 1., 1.]])
tensor([[-inf, -inf, 3., 4., 5.],
        [-inf, -inf, -inf, -inf, -inf]])
